# Generated by Django 3.2.7 on 2021-09-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyApp',
            new_name='SportNews',
        ),
    ]
