# Generated by Django 3.2.7 on 2021-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_dataregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataregistro',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataregistro',
            name='tel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sportnews',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
